### ISSUE TITLE
1

### ISSUE THREAD

**Issue by dogodefi** [Izumiko/redpill-loader-action#1]

**Comment by Izumiko** [comment]
我也不会逆向啥的，这个脚本只是修改了一下网上公开的那个docker版的

**Comment by dogodefi** [comment]
> 我也不会逆向啥的，这个脚本只是修改了一下网上公开的那个docker版的

没事呀，一起玩耍呀，我们也主要在做外围工作之类的，主要就是jumkey、unknown0和我

**Comment by Izumiko** [comment]
那行呀，进群划水😂
