### ISSUE TITLE
老哥，7.0.1怎么编译，这个是只能7.0吗

### ISSUE THREAD

**Issue by authon** [Izumiko/redpill-loader-action#2]
老哥，7.0.1怎么编译，这个是只能7.0吗

**Comment by Izumiko** [comment]
我只写了7.0的脚本，7.0.1的没写，你可以看看这个fork，他写了7.0.1的[sakurawill/redpill-loader-action](https://github.com/sakurawill/redpill-loader-action)

**Comment by sakurawill** [comment]
好像新版本redpill-virtio剥离了变成扩展后就无法编译了

**Comment by Izumiko** [comment]
@sakurawill 按TTG的[说明](https://github.com/RedPill-TTG/redpill-load/blob/master/docs/extensions-overview.md#using-extensions)，在config里加上virtio的设置试试。编译命令本身没啥变化，可以看一下redpill-load里面的编译脚本，在tools目录下
